/**
 * Product Seed V3
 * Adds 55+ new longevity products to bring total to ~100
 * Categories: peptides, hormones, diagnostics, devices, advanced supplements, pharmaceuticals, protocols
 */

import { KnowledgeBase } from '../kb/store.js';

const V3_PRODUCTS = [
  // ═══════════════════════════════════════
  // PEPTIDES & GROWTH FACTORS
  // ═══════════════════════════════════════
  {
    name: 'TB-500 (Thymosin Beta-4)',
    category: 'peptide',
    evidenceGrade: 'D',
    riskProfile: 'medium',
    description: 'Synthetic fragment of thymosin beta-4, a naturally occurring peptide involved in tissue repair and regeneration. Widely used in biohacking and veterinary medicine for accelerating wound healing and reducing inflammation. Limited human clinical data but extensive animal research.',
    mechanisms: ['Tissue repair and regeneration', 'Angiogenesis promotion', 'Anti-inflammatory', 'Actin regulation and cell migration'],
    dosage: { standard: '2.5mg twice weekly (injection)', range: '2-10mg/week', notes: 'Typically run in 4-6 week cycles. Subcutaneous injection. Not FDA approved for human use.' },
    keyFindings: ['Promoted cardiac repair after myocardial infarction in animal models', 'Accelerated wound healing and hair regrowth in preclinical studies', 'Upregulates actin polymerization enabling cell migration to injury sites'],
    interactions: ['May interact with anticoagulants due to wound-healing effects'],
    sideEffects: ['Injection site irritation', 'Headache', 'Lethargy'],
    contraindications: ['Active cancer (theoretical — promotes angiogenesis)', 'Pregnancy'],
    tags: ['peptide', 'healing', 'regeneration', 'experimental', 'biohacker'],
    estimatedMonthlyCost: { low: 40, mid: 80, high: 150, currency: 'USD' },
  },
  {
    name: 'DSIP (Delta Sleep-Inducing Peptide)',
    category: 'peptide',
    evidenceGrade: 'D',
    riskProfile: 'medium',
    description: 'A neuropeptide originally isolated from rabbit brain that promotes delta wave sleep. Research suggests roles in stress modulation, pain perception, and endocrine regulation. Limited but intriguing clinical data from European studies.',
    mechanisms: ['Delta wave sleep induction', 'Cortisol and stress modulation', 'LH/GH release regulation', 'Opioid system modulation'],
    dosage: { standard: '100-300mcg before bed (intranasal or injection)', range: '100-500mcg', notes: 'Short half-life. Typically used for 2-4 week cycles. Intranasal or subcutaneous.' },
    keyFindings: ['Improved sleep architecture and increased delta wave sleep in clinical studies', 'Normalized disturbed sleep patterns without next-day sedation', 'Showed stress-protective and analgesic properties in animal models'],
    interactions: ['May potentiate sedatives and sleep medications'],
    sideEffects: ['Mild drowsiness', 'Vivid dreams', 'Nasal irritation (intranasal)'],
    contraindications: ['Severe respiratory depression', 'Use of CNS depressants'],
    tags: ['peptide', 'sleep', 'stress', 'neuropeptide', 'experimental'],
    estimatedMonthlyCost: { low: 30, mid: 60, high: 120, currency: 'USD' },
  },
  {
    name: 'Selank',
    category: 'peptide',
    evidenceGrade: 'C',
    riskProfile: 'low',
    description: 'A synthetic analogue of the immunomodulatory peptide tuftsin, developed at the Institute of Molecular Genetics (Russia). Approved as an anxiolytic in Russia. Enhances BDNF expression and has nootropic and immune-modulating properties.',
    mechanisms: ['BDNF upregulation', 'GABA modulation', 'Immune system modulation (IL-6, T-helper balance)', 'Enkephalin stabilization'],
    dosage: { standard: '250-500mcg intranasal, 1-3x/day', range: '150-750mcg/day', notes: 'Intranasal administration. Approved in Russia. Typical course is 2-4 weeks.' },
    keyFindings: ['Approved anxiolytic in Russia with clinical trial data', 'Increased BDNF mRNA expression in hippocampus (animal studies)', 'Anxiolytic without sedation or cognitive impairment'],
    interactions: ['Theoretical interaction with benzodiazepines or other GABAergic drugs'],
    sideEffects: ['Nasal irritation', 'Mild fatigue (rare)'],
    contraindications: ['Pregnancy', 'Autoimmune conditions (theoretical)'],
    tags: ['peptide', 'nootropic', 'anxiolytic', 'immune', 'russian-research'],
    estimatedMonthlyCost: { low: 25, mid: 50, high: 100, currency: 'USD' },
  },
  {
    name: 'Semax',
    category: 'peptide',
    evidenceGrade: 'C',
    riskProfile: 'low',
    description: 'A synthetic analogue of ACTH(4-7) developed in Russia, approved for cognitive enhancement and neuroprotection. Enhances BDNF, NGF, and has robust nootropic effects. Extensively studied in Russian clinical settings for stroke recovery and cognitive decline.',
    mechanisms: ['BDNF and NGF upregulation', 'Dopamine and serotonin modulation', 'Neuroprotection via anti-inflammatory pathways', 'Improved cerebral blood flow'],
    dosage: { standard: '200-600mcg intranasal, 2-3x/day', range: '100-900mcg/day', notes: 'Intranasal drops or spray. Approved in Russia and Ukraine. 10-14 day courses typical.' },
    keyFindings: ['Improved cognitive performance and memory in clinical trials', 'Accelerated recovery from ischemic stroke in Russian clinical data', 'Upregulated BDNF expression by 4-8x in animal hippocampus'],
    interactions: ['May interact with stimulants or ADHD medications'],
    sideEffects: ['Nasal irritation', 'Mild headache', 'Irritability at high doses'],
    contraindications: ['Acute psychosis', 'Seizure disorders', 'Pregnancy'],
    tags: ['peptide', 'nootropic', 'neuroprotective', 'cognitive', 'russian-research'],
    estimatedMonthlyCost: { low: 20, mid: 45, high: 90, currency: 'USD' },
  },
  {
    name: 'GHK-Cu (Copper Peptide)',
    category: 'peptide',
    evidenceGrade: 'C',
    riskProfile: 'low',
    description: 'A naturally occurring copper-binding tripeptide that declines with age. Extensive research shows it remodels tissue, stimulates collagen and glycosaminoglycans, has anti-inflammatory effects, and may reset gene expression toward a younger pattern.',
    mechanisms: ['Collagen and elastin synthesis', 'Stem cell attraction to injury sites', 'Gene expression reset (resets ~30% of genes to younger pattern)', 'Anti-inflammatory and antioxidant'],
    dosage: { standard: '1-2ml of 0.1% solution topical, or 200mcg injection', range: 'Topical or 100-500mcg SC', notes: 'Topical for skin/hair. Subcutaneous injection for systemic effects. Naturally present in plasma at ~200ng/ml in youth.' },
    keyFindings: ['Resets expression of ~30% of human genes toward a younger state (Pickart)', 'Improved wound healing, skin thickness, and hair growth in clinical studies', 'Plasma levels decline from 200ng/ml (age 20) to 80ng/ml (age 60)'],
    interactions: ['Copper supplements — monitor copper levels'],
    sideEffects: ['Skin irritation (topical)', 'Injection site redness'],
    contraindications: ['Wilson disease (copper metabolism disorder)', 'Active liver disease'],
    tags: ['peptide', 'skin', 'regeneration', 'anti-aging', 'copper', 'gene-expression'],
    estimatedMonthlyCost: { low: 15, mid: 40, high: 100, currency: 'USD' },
  },
  {
    name: 'Thymosin Alpha-1',
    category: 'peptide',
    evidenceGrade: 'B',
    riskProfile: 'medium',
    description: 'A thymic peptide that modulates the immune system by stimulating T-cell maturation and function. FDA-approved as orphan drug (Zadaxin) for hepatitis B. Used clinically in over 30 countries for immunomodulation and shows promise for immune aging.',
    mechanisms: ['T-cell maturation and differentiation', 'Dendritic cell activation', 'NK cell enhancement', 'Toll-like receptor signaling modulation'],
    dosage: { standard: '1.6mg subcutaneous, 2x/week', range: '0.8-3.2mg, 2-3x/week', notes: 'Subcutaneous injection. FDA orphan drug approval. Used clinically in 30+ countries.' },
    keyFindings: ['Improved survival in sepsis and hepatitis B in multiple clinical trials', 'Enhanced vaccine response in immunocompromised elderly patients', 'Restored T-cell function in aging immune systems (immunosenescence)'],
    interactions: ['Immunosuppressants (may counteract)', 'Other immunomodulators'],
    sideEffects: ['Injection site reactions', 'Mild flu-like symptoms (rare)'],
    contraindications: ['Organ transplant recipients on immunosuppressants', 'Active autoimmune disease'],
    tags: ['peptide', 'immune', 'thymus', 'immunosenescence', 'clinical', 'approved'],
    estimatedMonthlyCost: { low: 100, mid: 250, high: 500, currency: 'USD' },
  },

  // ═══════════════════════════════════════
  // HORMONES & HORMONE SUPPORT
  // ═══════════════════════════════════════
  {
    name: 'Pregnenolone',
    category: 'supplement',
    evidenceGrade: 'C',
    riskProfile: 'medium',
    description: 'The "mother hormone" — precursor to all steroid hormones including DHEA, progesterone, cortisol, testosterone, and estrogen. Levels decline dramatically with age. Supports cognitive function, mood, and hormonal balance.',
    mechanisms: ['Steroid hormone precursor (all pathways)', 'GABA-A receptor modulation', 'NMDA receptor potentiation', 'Neurosteroid — enhances memory and cognition'],
    dosage: { standard: '30-50mg/day', range: '10-100mg/day', notes: 'Start low (10mg). Can convert to multiple downstream hormones. Monitor with blood tests. Take in morning.' },
    keyFindings: ['Levels decline ~60% between ages 35-75', 'Improved memory and cognitive performance in small human trials', 'Enhanced myelination and neuroplasticity in preclinical studies'],
    interactions: ['Hormone-sensitive conditions', 'Other hormone supplements (DHEA, progesterone)'],
    sideEffects: ['Acne', 'Hair loss (if converts heavily to androgens)', 'Mood changes', 'Overstimulation'],
    contraindications: ['Hormone-sensitive cancers (breast, prostate)', 'Pregnancy', 'Endometriosis'],
    tags: ['hormone', 'precursor', 'neurosteroid', 'cognitive', 'age-related-decline'],
    estimatedMonthlyCost: { low: 8, mid: 15, high: 30, currency: 'USD' },
  },
  {
    name: 'Melatonin (High-Dose Longevity)',
    category: 'supplement',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Higher-dose melatonin (3-20mg) used specifically for longevity and anti-cancer purposes, distinct from low-dose sleep use. Acts as a potent mitochondrial antioxidant, immune modulator, and has direct anti-cancer properties via oncostatic mechanisms.',
    mechanisms: ['Mitochondrial antioxidant (concentrates in mitochondria)', 'Oncostatic — inhibits cancer cell proliferation', 'Telomerase regulation', 'Autophagy induction at higher doses'],
    dosage: { standard: '5-10mg/night', range: '3-20mg/night', notes: 'Higher doses for longevity/anti-cancer distinct from sleep dose (0.3-1mg). Extended-release preferred. Take 1hr before bed.' },
    keyFindings: ['10mg dose showed anti-cancer effects as adjuvant therapy in multiple RCTs', 'Concentrates in mitochondria — 10x more potent there than in cytosol', 'Extended lifespan in multiple animal models at higher doses'],
    interactions: ['Immunosuppressants', 'Blood thinners', 'Diabetes medications (affects insulin sensitivity)'],
    sideEffects: ['Morning grogginess', 'Vivid dreams', 'Possible hormone disruption at very high doses'],
    contraindications: ['Autoimmune conditions (may stimulate immune system)', 'Depression (may worsen in some)'],
    tags: ['hormone', 'antioxidant', 'anti-cancer', 'mitochondria', 'longevity-dose', 'affordable'],
    estimatedMonthlyCost: { low: 5, mid: 12, high: 25, currency: 'USD' },
  },
  {
    name: 'Iodine (Lugol\'s / Nascent)',
    category: 'supplement',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Essential trace element critical for thyroid function, metabolism, and cellular health. Deficiency is widespread globally and linked to cognitive decline, metabolic dysfunction, and increased cancer risk. Supports thyroid hormone production (T3/T4).',
    mechanisms: ['Thyroid hormone synthesis (T3, T4)', 'Breast and prostate tissue health', 'Antioxidant in thyroid (via thyroid peroxidase)', 'Cellular detoxification (displaces halides)'],
    dosage: { standard: '150-300mcg/day', range: '150mcg-12.5mg/day', notes: 'RDA is 150mcg. Higher doses (mg range) controversial — requires selenium co-supplementation. Start low with thyroid monitoring.' },
    keyFindings: ['2 billion people worldwide are iodine deficient (WHO)', 'Japanese dietary intake (~1-3mg/day) associated with lower breast cancer rates', 'Essential for cognitive development and maintenance throughout life'],
    interactions: ['Thyroid medications (levothyroxine)', 'Lithium', 'Anti-thyroid drugs'],
    sideEffects: ['Thyroid dysfunction if excessive', 'Metallic taste', 'Skin breakouts (bromide detox)'],
    contraindications: ['Hashimoto thyroiditis (use with caution, low dose)', 'Hyperthyroidism', 'Thyroid nodules'],
    tags: ['mineral', 'thyroid', 'essential', 'metabolism', 'affordable', 'deficiency-common'],
    estimatedMonthlyCost: { low: 5, mid: 10, high: 20, currency: 'USD' },
  },

  // ═══════════════════════════════════════
  // TESTING & DIAGNOSTICS
  // ═══════════════════════════════════════
  {
    name: 'TruAge Epigenetic Test',
    category: 'diagnostic',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'DNA methylation-based biological age test using the TruAge PACE (DunedinPACE) algorithm. Measures the rate of aging rather than just biological age. Considered one of the most validated epigenetic clocks for tracking intervention effects.',
    mechanisms: ['DNA methylation analysis at CpG sites', 'DunedinPACE algorithm (rate of aging)', 'Epigenetic clock calibration'],
    dosage: { standard: 'Blood draw, test every 3-6 months', range: 'Quarterly to annually', notes: 'Uses whole blood sample. DunedinPACE measures pace of aging (1.0 = normal, <1.0 = slower aging). Track trends over time.' },
    keyFindings: ['DunedinPACE validated against 20-year longitudinal data (Dunedin Study)', 'Predicts mortality, morbidity, and functional decline', 'Responsive to lifestyle interventions within 6-12 months'],
    interactions: [],
    sideEffects: ['Venipuncture discomfort'],
    contraindications: [],
    tags: ['diagnostic', 'epigenetic', 'biological-age', 'methylation', 'tracking'],
    estimatedMonthlyCost: { low: 75, mid: 100, high: 125, currency: 'USD' },
  },
  {
    name: 'GlycanAge Test',
    category: 'diagnostic',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Biological age test based on IgG glycosylation patterns. Measures the glycan structures attached to immunoglobulin G, which reflect chronic inflammation and immune system aging. Complementary to epigenetic clocks.',
    mechanisms: ['IgG glycosylation analysis', 'Inflammation status assessment', 'Immune age measurement'],
    dosage: { standard: 'Dried blood spot, test every 3-6 months', range: 'Quarterly to annually', notes: 'Simple finger-prick dried blood spot. Measures glycan age (can be older or younger than chronological age). Responsive to lifestyle changes.' },
    keyFindings: ['IgG glycans change predictably with age and inflammation', 'Responsive to lifestyle interventions within 3-6 months (faster than methylation clocks)', 'Validated across multiple cohorts (>100,000 individuals)'],
    interactions: [],
    sideEffects: ['Finger prick discomfort'],
    contraindications: ['Active infection may skew results'],
    tags: ['diagnostic', 'glycan', 'biological-age', 'inflammation', 'immune-age'],
    estimatedMonthlyCost: { low: 50, mid: 75, high: 100, currency: 'USD' },
  },
  {
    name: 'Galleri Multi-Cancer Early Detection',
    category: 'diagnostic',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Blood test by GRAIL that screens for 50+ cancer types via cell-free DNA methylation patterns. Detects cancer signal and predicts tissue of origin. Designed as complement to standard screening, especially for cancers without current screening methods.',
    mechanisms: ['Cell-free DNA (cfDNA) methylation analysis', 'Cancer signal detection across 50+ types', 'Tissue of origin prediction'],
    dosage: { standard: 'Blood draw, annually', range: 'Annually', notes: 'Recommended for adults 50+ or high-risk individuals. Complement to (not replacement for) standard screenings. ~0.5% false positive rate.' },
    keyFindings: ['Detected 50+ cancer types with 51.5% sensitivity in PATHFINDER study', 'Predicted tissue of origin with 88% accuracy', 'NHS-Galleri trial (140,000 participants) — largest cancer screening trial ever'],
    interactions: [],
    sideEffects: ['Venipuncture', 'Psychological impact of results'],
    contraindications: ['Already undergoing cancer treatment (may confound results)'],
    tags: ['diagnostic', 'cancer-screening', 'liquid-biopsy', 'cfdna', 'preventive'],
    estimatedMonthlyCost: { low: 75, mid: 80, high: 85, currency: 'USD' },
  },
  {
    name: 'Comprehensive Blood Biomarker Panel',
    category: 'diagnostic',
    evidenceGrade: 'A',
    riskProfile: 'low',
    description: 'Extended blood panel covering metabolic, hormonal, inflammatory, and organ function markers. Goes beyond standard annual bloodwork to include longevity-relevant biomarkers like insulin, hs-CRP, homocysteine, ApoB, and hormone panels.',
    mechanisms: ['Metabolic health assessment (glucose, insulin, HbA1c, lipids)', 'Inflammation markers (hs-CRP, homocysteine, IL-6)', 'Hormone levels (testosterone, estradiol, thyroid, cortisol)', 'Organ function (liver, kidney, complete blood count)'],
    dosage: { standard: 'Fasting blood draw, every 3-6 months', range: 'Quarterly to annually', notes: 'Best done fasting (12hr). Include: CBC, CMP, lipid panel + ApoB, insulin, HbA1c, hs-CRP, homocysteine, full thyroid, hormones, vitamin D, B12, ferritin.' },
    keyFindings: ['Regular monitoring enables data-driven intervention optimization', 'ApoB superior to LDL-C for cardiovascular risk assessment', 'Fasting insulin is earliest marker of metabolic dysfunction'],
    interactions: [],
    sideEffects: ['Venipuncture discomfort', 'Fasting requirement'],
    contraindications: [],
    tags: ['diagnostic', 'blood-test', 'biomarkers', 'tracking', 'essential', 'preventive'],
    estimatedMonthlyCost: { low: 50, mid: 100, high: 200, currency: 'USD' },
  },

  // ═══════════════════════════════════════
  // DEVICES & TECHNOLOGY
  // ═══════════════════════════════════════
  {
    name: 'Red Light Therapy Panel',
    category: 'device',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Photobiomodulation devices emitting red (630-670nm) and near-infrared (810-850nm) light. Stimulates mitochondrial cytochrome c oxidase, increasing ATP production and reducing oxidative stress. Studied for skin health, wound healing, pain reduction, and cognitive function.',
    mechanisms: ['Cytochrome c oxidase stimulation (Complex IV)', 'ATP production increase', 'Reactive oxygen species signaling (hormetic)', 'Nitric oxide release and blood flow'],
    dosage: { standard: '10-20min per session, 5-10cm from panel, daily', range: '5-30min, 3-7x/week', notes: 'Red (660nm) for skin/surface. NIR (850nm) penetrates deeper for joints, brain. Power density 50-100mW/cm². Quality panels: Joovv, Mito Red, Platinum LED.' },
    keyFindings: ['Improved skin complexion, collagen density, and wrinkle reduction in RCTs', 'Reduced joint pain and inflammation comparable to NSAIDs in some trials', 'Enhanced cognitive function and reduced TBI symptoms (Naeser et al.)'],
    interactions: ['Photosensitizing medications'],
    sideEffects: ['Temporary skin warmth', 'Eye strain (use goggles)', 'Rare: headache'],
    contraindications: ['Active cancer over treatment area (theoretical)', 'Photosensitivity disorders', 'Over thyroid if hyperthyroid'],
    tags: ['device', 'photobiomodulation', 'mitochondria', 'skin', 'pain', 'recovery'],
    estimatedMonthlyCost: { low: 0, mid: 0, high: 0, currency: 'USD' },
  },
  {
    name: 'Hyperbaric Oxygen Chamber (HBOT)',
    category: 'device',
    evidenceGrade: 'B',
    riskProfile: 'medium',
    description: 'Pressurized chamber delivering 100% oxygen at 1.3-2.0 ATA. Increases dissolved oxygen in plasma, stimulates stem cell release, promotes angiogenesis, and has shown remarkable results in reversing biological aging markers in clinical trials.',
    mechanisms: ['Hyperoxia-hypoxia paradox (stem cell mobilization)', 'Telomere lengthening', 'Senescent cell clearance', 'Angiogenesis and neuroplasticity'],
    dosage: { standard: '60-90min at 1.5-2.0 ATA, 2-5x/week', range: '40-120min sessions', notes: 'Clinical HBOT at 2.0 ATA requires prescription. Mild HBOT (1.3 ATA) available for home use. Tel Aviv protocol: 60 sessions for anti-aging.' },
    keyFindings: ['Lengthened telomeres by 20-38% and cleared senescent cells by 11-37% (Hadanny 2020, Tel Aviv)', 'Improved cognitive function in elderly with MCI in randomized trial', 'FDA-approved for 14 conditions including wound healing and carbon monoxide poisoning'],
    interactions: ['Certain chemotherapy drugs', 'Bleomycin (pulmonary toxicity risk)'],
    sideEffects: ['Ear barotrauma', 'Sinus pressure', 'Temporary myopia', 'Claustrophobia'],
    contraindications: ['Untreated pneumothorax', 'Certain lung conditions', 'Recent ear surgery'],
    tags: ['device', 'oxygen', 'telomere', 'senolytic', 'regeneration', 'clinical'],
    estimatedMonthlyCost: { low: 200, mid: 600, high: 1500, currency: 'USD' },
  },
  {
    name: 'Cold Plunge (Equipment)',
    category: 'device',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Dedicated cold water immersion equipment maintaining water at 1-15°C. Provides consistent cold exposure for hormesis, brown fat activation, and mood enhancement. Ranges from simple ice barrels to chiller-equipped tubs with filtration.',
    mechanisms: ['Norepinephrine surge (2-3x baseline)', 'Brown adipose tissue activation', 'Cold shock proteins (RBM3)', 'Vagal tone improvement'],
    dosage: { standard: '2-5min at 10-15°C, 3-5x/week', range: '1-15min, based on temperature and adaptation', notes: 'Colder = shorter. 11°C Huberman protocol. Do NOT warm up with hot shower after — let body reheat naturally for maximum brown fat effect.' },
    keyFindings: ['2-3x norepinephrine increase lasting hours (sustained mood/focus boost)', 'Activated brown fat and increased metabolic rate in regular practitioners', 'Cold shock protein RBM3 associated with neuroprotection and synaptogenesis'],
    interactions: [],
    sideEffects: ['Cold shock response (initial)', 'Hyperventilation risk', 'Numbness'],
    contraindications: ['Uncontrolled cardiovascular disease', 'Raynaud phenomenon (severe)', 'Cold urticaria'],
    tags: ['device', 'cold-exposure', 'hormesis', 'brown-fat', 'norepinephrine'],
    estimatedMonthlyCost: { low: 0, mid: 0, high: 0, currency: 'USD' },
  },
  {
    name: 'Infrared Sauna',
    category: 'device',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Far-infrared (FIR) sauna panels that heat the body directly at lower ambient temperatures (40-65°C) compared to traditional Finnish saunas. Promotes detoxification, cardiovascular conditioning, and heat shock protein production with better tolerability.',
    mechanisms: ['Heat shock protein induction (HSP70, HSP90)', 'Increased core body temperature', 'Heavy metal and toxin excretion via sweat', 'Cardiovascular conditioning (mimics moderate exercise)'],
    dosage: { standard: '30-45min at 55-65°C, 3-5x/week', range: '20-60min sessions', notes: 'Lower temperature than Finnish sauna but longer sessions. Far-infrared penetrates 1.5 inches into tissue. Hydrate well. Mineral supplementation recommended.' },
    keyFindings: ['Similar cardiovascular benefits to Finnish sauna at more tolerable temperatures', 'Improved symptoms in congestive heart failure patients (Waon therapy, Japan)', 'Enhanced detoxification — heavy metals and BPA found in sweat at higher concentrations than blood'],
    interactions: ['Heat-sensitive medications', 'Alcohol (dangerous combination)'],
    sideEffects: ['Dehydration', 'Electrolyte imbalance', 'Lightheadedness'],
    contraindications: ['Unstable angina', 'Recent heart attack', 'Pregnancy', 'Multiple sclerosis (heat-sensitive)'],
    tags: ['device', 'sauna', 'infrared', 'heat-shock', 'detox', 'cardiovascular'],
    estimatedMonthlyCost: { low: 0, mid: 0, high: 0, currency: 'USD' },
  },
  {
    name: 'Continuous Glucose Monitor (CGM)',
    category: 'device',
    evidenceGrade: 'A',
    riskProfile: 'low',
    description: 'Wearable sensor (usually on arm) that continuously tracks interstitial glucose levels, providing real-time data on metabolic health. Reveals hidden glucose spikes from foods, exercise, stress, and sleep. Key tool for metabolic optimization even in non-diabetics.',
    mechanisms: ['Real-time glucose monitoring (every 1-5 min)', 'Pattern recognition for food responses', 'Glucose variability tracking', 'Metabolic health optimization feedback'],
    dosage: { standard: 'Continuous wear, 14-day sensor', range: 'Ongoing or periodic 1-3 month experiments', notes: 'Major brands: Dexcom G7, Abbott Freestyle Libre 3, Stelo (OTC). Non-diabetics: use for 1-3 months to learn personal responses, then periodically recheck.' },
    keyFindings: ['Reveals individual glucose responses vary enormously to identical foods (Zeevi et al., Cell)', 'Glucose variability (not just average) predicts cardiovascular risk', 'Behavior change tool — users reduce glucose spikes 15-30% through real-time feedback'],
    interactions: ['High-dose vitamin C may interfere with readings', 'Acetaminophen (older sensors)'],
    sideEffects: ['Skin irritation at sensor site', 'Adhesive allergy'],
    contraindications: ['Severe skin conditions at application site'],
    tags: ['device', 'cgm', 'glucose', 'metabolic', 'wearable', 'tracking', 'data-driven'],
    estimatedMonthlyCost: { low: 75, mid: 125, high: 200, currency: 'USD' },
  },
  {
    name: 'Oura Ring',
    category: 'device',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Smart ring wearable tracking sleep stages, HRV, resting heart rate, body temperature, blood oxygen, and activity. Provides daily readiness and sleep scores. Compact form factor with research-grade accuracy for sleep tracking.',
    mechanisms: ['Photoplethysmography (PPG) for heart rate and HRV', 'Accelerometer for sleep staging and activity', 'Temperature sensor (deviation tracking)', 'SpO2 monitoring'],
    dosage: { standard: 'Continuous wear, charge every 4-7 days', range: 'Daily use', notes: 'Gen 3. Best sleep tracker available in wearable form. HRV and temperature trends most valuable for longevity tracking. Pairs with app for insights.' },
    keyFindings: ['94.1% agreement with polysomnography for sleep staging', 'Detected COVID-19 onset 2.75 days before symptoms via temperature deviation', 'HRV tracking correlates with autonomic nervous system health and recovery'],
    interactions: [],
    sideEffects: ['Finger irritation (rare)', 'Anxiety from over-monitoring (orthosomnia)'],
    contraindications: [],
    tags: ['device', 'wearable', 'sleep', 'hrv', 'tracking', 'temperature'],
    estimatedMonthlyCost: { low: 6, mid: 6, high: 6, currency: 'USD' },
  },
  {
    name: 'WHOOP Band',
    category: 'device',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Continuous physiological monitoring wearable focused on strain, recovery, and sleep. Uses HRV, resting heart rate, respiratory rate, and skin temperature to calculate daily recovery scores. Popular among athletes and biohackers for training optimization.',
    mechanisms: ['HRV-based recovery scoring', 'Strain tracking (cardiovascular load)', 'Sleep performance analysis', 'Respiratory rate monitoring'],
    dosage: { standard: 'Continuous wear, membership model', range: 'Daily use', notes: 'WHOOP 4.0. No screen — purely data-focused. Subscription model ($30/month). Best for training optimization and recovery tracking. Journal feature for behavior correlation.' },
    keyFindings: ['HRV-guided training improved performance outcomes vs fixed programs', 'Respiratory rate changes detected illness onset early', 'Strain-recovery balance optimization reduces overtraining risk'],
    interactions: [],
    sideEffects: ['Skin irritation under band', 'Data anxiety in some users'],
    contraindications: [],
    tags: ['device', 'wearable', 'hrv', 'recovery', 'training', 'strain'],
    estimatedMonthlyCost: { low: 30, mid: 30, high: 30, currency: 'USD' },
  },

  // ═══════════════════════════════════════
  // ADVANCED SUPPLEMENTS
  // ═══════════════════════════════════════
  {
    name: 'Fisetin (High-Dose Senolytic)',
    category: 'supplement',
    evidenceGrade: 'C',
    riskProfile: 'low',
    description: 'High-dose fisetin protocol (500-2000mg) used intermittently as a senolytic to clear senescent cells. Distinct from daily low-dose use. The "senolytic hit" approach targets zombie cells during 1-3 day bursts, followed by weeks of clearance.',
    mechanisms: ['Senolytic — kills senescent cells via apoptosis', 'Bcl-2 family inhibition in senescent cells', 'PI3K/AKT pathway modulation', 'SASP reduction'],
    dosage: { standard: '1000-2000mg/day for 2 consecutive days, monthly', range: '500-2500mg over 1-3 days', notes: 'Senolytic dosing is HIGH and INTERMITTENT. Different from daily use. Take with fat (olive oil) for absorption. Mayo Clinic trial used 20mg/kg.' },
    keyFindings: ['Most potent senolytic identified in natural compound screen (Mayo Clinic)', 'AFFIRM-LITE trial: high-dose fisetin for senescent cell clearance', 'Intermittent dosing allows immune clearance of dead senescent cells between rounds'],
    interactions: ['Blood thinners (high doses may affect platelet function)', 'CYP3A4 substrates'],
    sideEffects: ['GI discomfort at high doses', 'Diarrhea', 'Possible allergic reaction'],
    contraindications: ['Bleeding disorders', 'Upcoming surgery'],
    tags: ['supplement', 'senolytic', 'intermittent', 'high-dose', 'anti-aging'],
    estimatedMonthlyCost: { low: 20, mid: 40, high: 80, currency: 'USD' },
  },
  {
    name: 'Luteolin',
    category: 'supplement',
    evidenceGrade: 'C',
    riskProfile: 'low',
    description: 'Flavonoid found in celery, peppers, and chamomile with potent anti-neuroinflammatory and mast cell stabilizing properties. Crosses the blood-brain barrier and inhibits microglial activation, making it particularly relevant for brain aging and neuroinflammation.',
    mechanisms: ['Mast cell stabilization', 'Microglial inhibition', 'NF-κB suppression', 'Nrf2 activation'],
    dosage: { standard: '100-200mg/day', range: '50-400mg/day', notes: 'Liposomal form for better absorption. Found in celery seed, chamomile, peppers. Often combined with rutin for synergy.' },
    keyFindings: ['Potent inhibitor of microglial activation and neuroinflammation', 'Improved cognitive function in brain fog and post-viral syndromes', 'Crosses blood-brain barrier — one of few flavonoids that does effectively'],
    interactions: ['CYP3A4 and CYP1A2 substrates (may inhibit metabolism)'],
    sideEffects: ['Mild GI upset', 'Headache (rare)'],
    contraindications: ['Pregnancy (insufficient data)'],
    tags: ['supplement', 'flavonoid', 'neuroinflammation', 'mast-cell', 'brain'],
    estimatedMonthlyCost: { low: 10, mid: 20, high: 40, currency: 'USD' },
  },
  {
    name: 'Alpha-GPC',
    category: 'supplement',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Most bioavailable choline source, crossing the blood-brain barrier efficiently. Supports acetylcholine synthesis, cognitive function, and growth hormone release. Used clinically in Europe for cognitive decline and as a nootropic in the biohacking community.',
    mechanisms: ['Acetylcholine precursor', 'Phosphatidylcholine synthesis', 'Growth hormone potentiation', 'Cell membrane integrity'],
    dosage: { standard: '300-600mg/day', range: '150-1200mg/day', notes: 'Take in morning or pre-workout. 600mg pre-exercise may boost GH. Pharmaceutical grade (Gliatilin) used in Europe for dementia. Hygroscopic — keep dry.' },
    keyFindings: ['Improved cognitive function in Alzheimer patients in multiple Italian trials', 'Acute 600mg dose increased growth hormone secretion', 'Superior choline delivery to brain compared to choline bitartrate or CDP-choline'],
    interactions: ['Acetylcholinesterase inhibitors (additive effect)', 'Scopolamine'],
    sideEffects: ['Headache', 'GI upset', 'Insomnia if taken late', 'Fishy body odor (rare, high doses)'],
    contraindications: ['Active peptic ulcer'],
    tags: ['supplement', 'nootropic', 'choline', 'cognitive', 'growth-hormone'],
    estimatedMonthlyCost: { low: 12, mid: 25, high: 45, currency: 'USD' },
  },
  {
    name: 'Lion\'s Mane (Hericium erinaceus)',
    category: 'supplement',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Medicinal mushroom with unique neurotrophic properties. Contains hericenones and erinacines that stimulate Nerve Growth Factor (NGF) synthesis — the only known natural compounds to do so. Supports neurogenesis, cognition, and may protect against neurodegeneration.',
    mechanisms: ['NGF stimulation (hericenones and erinacines)', 'BDNF upregulation', 'Neurogenesis promotion', 'Anti-inflammatory and neuroprotective'],
    dosage: { standard: '500-1000mg extract, 2x/day', range: '500-3000mg/day', notes: 'Dual extract (hot water + alcohol) captures both hericenones and erinacines. Fruiting body + mycelium combined preferred. Take consistently for 4+ weeks for cognitive effects.' },
    keyFindings: ['Improved cognitive function in mild cognitive impairment (Mori et al., double-blind RCT)', 'Stimulated NGF synthesis in human astrocyte cells', 'Reduced anxiety and depression scores in menopausal women'],
    interactions: ['Blood thinners (mild antiplatelet effect)', 'Diabetes medications (may lower blood sugar)'],
    sideEffects: ['GI discomfort', 'Skin rash (rare, in allergic individuals)'],
    contraindications: ['Mushroom allergy', 'Pre-surgery (antiplatelet effect)'],
    tags: ['supplement', 'mushroom', 'nootropic', 'ngf', 'neurogenesis', 'cognitive'],
    estimatedMonthlyCost: { low: 15, mid: 30, high: 60, currency: 'USD' },
  },
  {
    name: 'Taurine (Longevity Dose)',
    category: 'supplement',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Semi-essential amino acid that declines dramatically with age. A landmark 2023 Science paper showed taurine supplementation extended lifespan in mice by 10-12% and improved healthspan across multiple systems. Higher "longevity doses" (1-6g) differ from typical supplement amounts.',
    mechanisms: ['Mitochondrial function support', 'Anti-inflammatory (reduces oxidative stress)', 'Osmotic regulation and calcium signaling', 'Bile acid conjugation'],
    dosage: { standard: '1-3g/day', range: '1-6g/day', notes: 'Science 2023 paper used ~500-1000mg/kg in mice (human equivalent ~3-6g). Levels decline 80% with age. Take with meals. Very affordable.' },
    keyFindings: ['Extended median lifespan by 10-12% in mice (Singh et al., Science 2023)', 'Blood taurine levels decline 80%+ from youth to old age', 'Improved bone density, muscle endurance, immune function, and metabolic health in aged mice'],
    interactions: ['Lithium (taurine affects renal lithium clearance)'],
    sideEffects: ['GI discomfort at very high doses', 'Mild drowsiness'],
    contraindications: ['Bipolar disorder on lithium (monitor levels)'],
    tags: ['supplement', 'amino-acid', 'longevity', 'Science-2023', 'affordable', 'age-related-decline'],
    estimatedMonthlyCost: { low: 5, mid: 10, high: 20, currency: 'USD' },
  },
  {
    name: 'TMG (Trimethylglycine / Betaine)',
    category: 'supplement',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Methyl donor that supports the methionine-homocysteine cycle, helping to lower homocysteine and support SAM (S-adenosylmethionine) production. Important companion to NMN/NR supplementation to replenish methyl groups consumed in NAD+ metabolism.',
    mechanisms: ['Methyl group donation (homocysteine → methionine)', 'SAM production support', 'Liver health (lipotropic)', 'Osmolyte function (cellular protection)'],
    dosage: { standard: '500-1000mg/day', range: '250-3000mg/day', notes: 'Essential co-supplement with NMN/NR to avoid methyl donor depletion. Also known as betaine (from beets). Take with meals. Very affordable.' },
    keyFindings: ['Effectively lowers homocysteine levels (independent cardiovascular risk factor)', 'Compensates for methyl group depletion from NAD+ precursor supplementation', 'Protects against fatty liver disease in clinical studies'],
    interactions: ['Methotrexate', 'Other methyl donors (folate, B12)'],
    sideEffects: ['GI upset', 'Fishy body odor (rare)', 'Nausea at high doses'],
    contraindications: ['Homocystinuria (need medical supervision)'],
    tags: ['supplement', 'methyl-donor', 'homocysteine', 'liver', 'nad-companion', 'affordable'],
    estimatedMonthlyCost: { low: 5, mid: 10, high: 20, currency: 'USD' },
  },
  {
    name: 'Ca-AKG (Calcium Alpha-Ketoglutarate)',
    category: 'supplement',
    evidenceGrade: 'C',
    riskProfile: 'low',
    description: 'Calcium salt of alpha-ketoglutarate, a key TCA cycle metabolite. The CALERIE-adjacent Rejuvant study showed biological age reversal. Supports epigenetic regulation via TET enzyme cofaction and collagen synthesis. Branded version: Rejuvant (ProHealthspan).',
    mechanisms: ['TCA cycle metabolite (energy production)', 'TET enzyme cofactor (DNA demethylation)', 'Collagen synthesis', 'Stem cell maintenance'],
    dosage: { standard: '1000mg/day', range: '500-2000mg/day', notes: 'Calcium alpha-ketoglutarate specific form. Take on empty stomach. Rejuvant brand is most studied. May take 4-7 months for measurable epigenetic changes.' },
    keyFindings: ['Reduced biological age by 8 years in 7-month Rejuvant trial (TruAge)', 'Extended lifespan ~12% in mice and reduced frailty (Buck Institute)', 'AKG levels decline 10-fold between ages 40 and 80'],
    interactions: ['Calcium supplements (additive calcium intake)'],
    sideEffects: ['Mild GI discomfort', 'Constipation (calcium component)'],
    contraindications: ['Hypercalcemia', 'Kidney stones (calcium-based)'],
    tags: ['supplement', 'metabolite', 'epigenetic', 'biological-age', 'tca-cycle', 'rejuvant'],
    estimatedMonthlyCost: { low: 30, mid: 50, high: 80, currency: 'USD' },
  },

  // ═══════════════════════════════════════
  // PHARMACEUTICALS (Rx)
  // ═══════════════════════════════════════
  {
    name: 'Acarbose',
    category: 'pharmaceutical',
    evidenceGrade: 'B',
    riskProfile: 'medium',
    description: 'Alpha-glucosidase inhibitor that slows carbohydrate digestion, reducing postprandial glucose spikes. One of only four drugs to extend lifespan in the NIA Interventions Testing Program (ITP) in mice. Particularly effective in males. Prescription required.',
    mechanisms: ['Alpha-glucosidase inhibition (slows starch digestion)', 'Post-prandial glucose spike reduction', 'Gut microbiome modulation', 'AMPK activation (indirect)'],
    dosage: { standard: '25-50mg with each meal', range: '25-100mg per meal', notes: 'Start at 25mg to minimize GI side effects. Take with first bite of food. Prescription drug. NIA ITP positive result.' },
    keyFindings: ['Extended lifespan in male mice by ~22% in NIA ITP (one of only 4 positive drugs)', 'Reduced cardiovascular events by 49% in STOP-NIDDM trial', 'Flattens postprandial glucose curve — "carb blocker" with longevity benefits'],
    interactions: ['Digestive enzymes (counteract each other)', 'Insulin and sulfonylureas (hypoglycemia risk)', 'Charcoal and absorbents'],
    sideEffects: ['Flatulence (common, usually improves)', 'Bloating', 'Diarrhea', 'Abdominal discomfort'],
    contraindications: ['Inflammatory bowel disease', 'Intestinal obstruction', 'Severe renal impairment', 'Cirrhosis'],
    tags: ['pharmaceutical', 'glucose', 'itp-positive', 'longevity-drug', 'prescription'],
    estimatedMonthlyCost: { low: 10, mid: 25, high: 50, currency: 'USD' },
  },
  {
    name: 'Low-Dose Lithium (Pharmaceutical)',
    category: 'pharmaceutical',
    evidenceGrade: 'C',
    riskProfile: 'low',
    description: 'Lithium at sub-therapeutic doses (150-300mcg to 5mg) for neuroprotection and longevity, far below psychiatric doses (600-1200mg). Population studies show lower all-cause mortality and dementia rates in regions with higher lithium in drinking water.',
    mechanisms: ['GSK-3β inhibition', 'Autophagy induction (TFEB activation)', 'BDNF upregulation', 'Neuroprotective — reduces neuroinflammation'],
    dosage: { standard: '1-5mg lithium orotate daily', range: '150mcg-20mg/day', notes: 'Sub-therapeutic dose — NOT psychiatric dosing. Lithium orotate preferred (better CNS penetration at low doses). No blood level monitoring needed at these doses.' },
    keyFindings: ['Higher lithium in drinking water associated with lower suicide, dementia, and all-cause mortality', 'Extended lifespan in C. elegans and Drosophila models', 'Low-dose lithium reduced biomarkers of Alzheimer disease progression'],
    interactions: ['NSAIDs (increase lithium levels)', 'ACE inhibitors', 'Diuretics'],
    sideEffects: ['Minimal at microdoses', 'Mild thirst (occasionally)', 'GI discomfort (rare)'],
    contraindications: ['Severe renal impairment', 'Addison disease', 'Brugada syndrome'],
    tags: ['pharmaceutical', 'neuroprotective', 'autophagy', 'low-dose', 'dementia-prevention'],
    estimatedMonthlyCost: { low: 5, mid: 10, high: 20, currency: 'USD' },
  },
  {
    name: 'Telmisartan',
    category: 'pharmaceutical',
    evidenceGrade: 'B',
    riskProfile: 'medium',
    description: 'Angiotensin II receptor blocker (ARB) with unique PPAR-γ partial agonist activity. Beyond blood pressure control, activates metabolic pathways similar to caloric restriction. Among the longest-acting ARBs with 24hr coverage. Popular in longevity medicine even for normotensive individuals.',
    mechanisms: ['Angiotensin II receptor blockade', 'PPAR-γ partial agonism (metabolic benefits)', 'Insulin sensitivity improvement', 'Anti-inflammatory and antifibrotic'],
    dosage: { standard: '20-40mg/day', range: '20-80mg/day', notes: 'Prescription required. Unique among ARBs for PPAR-γ activation. 24-hour half-life. Can be used at low dose (20mg) even without hypertension. Peter Attia protocols mention it.' },
    keyFindings: ['ONTARGET trial: comparable to ACE inhibitor ramipril for cardiovascular protection', 'Unique PPAR-γ agonism improves insulin sensitivity — not seen with other ARBs', 'Reduced new-onset diabetes by 30% compared to other antihypertensives'],
    interactions: ['Potassium supplements (hyperkalemia risk)', 'NSAIDs (reduced efficacy)', 'Lithium (increased levels)', 'Other antihypertensives'],
    sideEffects: ['Dizziness', 'Hypotension', 'Hyperkalemia', 'Back pain'],
    contraindications: ['Pregnancy (teratogenic)', 'Bilateral renal artery stenosis', 'Severe hepatic impairment'],
    tags: ['pharmaceutical', 'arb', 'metabolic', 'ppar-gamma', 'cardiovascular', 'prescription'],
    estimatedMonthlyCost: { low: 5, mid: 15, high: 30, currency: 'USD' },
  },
  {
    name: 'Canagliflozin (SGLT2 Inhibitor)',
    category: 'pharmaceutical',
    evidenceGrade: 'B',
    riskProfile: 'medium',
    description: 'SGLT2 inhibitor that blocks glucose reabsorption in kidneys, causing glycosuria (glucose excretion in urine). Extended lifespan in the NIA ITP. Beyond diabetes, shows remarkable cardio-renal protective effects and mimics aspects of caloric restriction.',
    mechanisms: ['SGLT2 inhibition (renal glucose excretion)', 'Caloric restriction mimetic (~200-300 cal/day excreted)', 'Ketogenesis promotion', 'Cardiovascular and renal protection'],
    dosage: { standard: '100mg/day', range: '100-300mg/day', notes: 'Prescription. ITP-positive for lifespan extension. CREDENCE and CANVAS trials. Causes glycosuria — keep hydrated. Monitor for UTIs.' },
    keyFindings: ['Extended lifespan in male mice in NIA ITP (genetically heterogeneous)', 'CANVAS program: 14% reduction in cardiovascular events', 'CREDENCE: 30% reduction in kidney disease progression'],
    interactions: ['Insulin and sulfonylureas (hypoglycemia risk)', 'Diuretics (volume depletion)', 'Loop diuretics'],
    sideEffects: ['Genital mycotic infections (yeast)', 'UTIs', 'Polyuria', 'Hypotension', 'DKA (rare)'],
    contraindications: ['Severe renal impairment (eGFR <30)', 'Type 1 diabetes', 'Recurrent UTIs or genital infections'],
    tags: ['pharmaceutical', 'sglt2', 'itp-positive', 'longevity-drug', 'cardiovascular', 'renal', 'prescription'],
    estimatedMonthlyCost: { low: 15, mid: 40, high: 100, currency: 'USD' },
  },
  {
    name: '17-alpha Estradiol',
    category: 'pharmaceutical',
    evidenceGrade: 'C',
    riskProfile: 'medium',
    description: 'Non-feminizing enantiomer of estradiol that extended lifespan in male mice in the NIA ITP. Unlike 17-beta estradiol, it does not activate classical estrogen receptors significantly, avoiding feminizing effects. Mechanism likely involves metabolic and hypothalamic pathways.',
    mechanisms: ['Hypothalamic nutrient sensing modulation', 'Hepatic lipid metabolism improvement', 'Visceral fat reduction', 'Non-classical estrogen signaling'],
    dosage: { standard: '4.8-14.4 ppm in diet (mouse dose — human equivalent uncertain)', range: 'Under investigation', notes: 'NIA ITP positive in males only. Human dosing not established. Available as compounded pharmaceutical. Mechanism distinct from classical estrogen receptor activation.' },
    keyFindings: ['Extended lifespan 19% in male mice in NIA ITP (no effect in females)', 'Did not feminize male mice — distinct from 17-beta estradiol', 'Improved glucose tolerance and reduced visceral adiposity in male mice'],
    interactions: ['Unknown — limited human data', 'Potentially liver-metabolized drugs'],
    sideEffects: ['Unknown in humans at longevity doses', 'Theoretical: mild estrogenic effects'],
    contraindications: ['Hormone-sensitive cancers', 'Women (untested for longevity)', 'Liver disease'],
    tags: ['pharmaceutical', 'itp-positive', 'longevity-drug', 'estrogen', 'experimental', 'males-only'],
    estimatedMonthlyCost: { low: 20, mid: 50, high: 100, currency: 'USD' },
  },
  {
    name: 'GLP-1 Receptor Agonists (Semaglutide)',
    category: 'pharmaceutical',
    evidenceGrade: 'A',
    riskProfile: 'medium',
    description: 'GLP-1 receptor agonist (Ozempic/Wegovy) originally for diabetes/obesity showing remarkable multi-organ benefits. Beyond weight loss, reduces cardiovascular events, kidney disease progression, and shows anti-inflammatory and neuroprotective effects. Being studied for Alzheimer prevention.',
    mechanisms: ['GLP-1 receptor agonism', 'Appetite suppression (hypothalamic)', 'Insulin secretion enhancement', 'Systemic anti-inflammatory effects'],
    dosage: { standard: '0.25-2.4mg weekly (subcutaneous injection)', range: '0.25-2.4mg/week', notes: 'Prescription. Titrate slowly over 16+ weeks to minimize GI side effects. Weekly injection. Wegovy (obesity dose up to 2.4mg) vs Ozempic (diabetes dose up to 2mg).' },
    keyFindings: ['SELECT trial: 20% reduction in major cardiovascular events in non-diabetic obese', 'FLOW trial: 24% reduction in kidney disease progression', 'Multiple ongoing trials for Alzheimer disease and NASH/liver disease'],
    interactions: ['Insulin (hypoglycemia risk)', 'Oral contraceptives (delayed absorption)', 'Other diabetes medications'],
    sideEffects: ['Nausea (common, usually transient)', 'Vomiting', 'Diarrhea', 'Pancreatitis (rare)', 'Muscle loss (requires resistance training)'],
    contraindications: ['Personal/family history of medullary thyroid carcinoma', 'MEN2 syndrome', 'Pancreatitis history', 'Gastroparesis'],
    tags: ['pharmaceutical', 'glp1', 'obesity', 'cardiovascular', 'prescription', 'blockbuster'],
    estimatedMonthlyCost: { low: 300, mid: 800, high: 1300, currency: 'USD' },
  },

  // ═══════════════════════════════════════
  // PROTOCOLS
  // ═══════════════════════════════════════
  {
    name: 'Bryan Johnson Blueprint Protocol',
    category: 'protocol',
    evidenceGrade: 'C',
    riskProfile: 'medium',
    description: 'Comprehensive anti-aging protocol by tech entrepreneur Bryan Johnson, aiming to achieve the body of an 18-year-old. Involves 100+ supplements, strict diet (1,977 calories vegan), extensive exercise, precise sleep optimization, and regular biomarker testing. Reported biological age reversal of 5+ years.',
    mechanisms: ['Multi-system optimization', 'Epigenetic age reversal', 'Caloric restriction with optimal nutrition', 'Comprehensive biomarker-driven adjustments'],
    dosage: { standard: 'Full protocol: 100+ daily interventions', range: 'Tiered: Blueprint Lite to Full', notes: 'Full protocol costs $2M+/year. Core elements (diet, sleep, exercise, key supplements) achievable for much less. Published openly at blueprint.bryanjohnson.com.' },
    keyFindings: ['Reported epigenetic age reversal of 5.1 years', 'Achieved top 1% fitness metrics across all organs tested', 'Documented extensively with public biomarker data — unprecedented n=1 experiment'],
    interactions: ['Complexity makes interaction tracking difficult'],
    sideEffects: ['Social isolation', 'Extreme rigidity', 'Financial burden (full protocol)'],
    contraindications: ['Eating disorder history', 'Financial constraints (full protocol)'],
    tags: ['protocol', 'comprehensive', 'blueprint', 'epigenetic', 'data-driven', 'extreme'],
    estimatedMonthlyCost: { low: 200, mid: 1000, high: 5000, currency: 'USD' },
  },
  {
    name: 'Peter Attia Longevity Framework',
    category: 'protocol',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Evidence-based longevity framework by physician Peter Attia MD (author of "Outlive"). Focuses on the "four horsemen" of chronic disease prevention through exercise (Zone 2 + strength), metabolic health, sleep optimization, and emotional health. Emphasizes Medicine 3.0 — proactive rather than reactive healthcare.',
    mechanisms: ['VO2max optimization (strongest mortality predictor)', 'Stability and strength training', 'Metabolic health optimization', 'Early cancer and cardiovascular screening'],
    dosage: { standard: '3-4hr/week Zone 2, 3-4 strength sessions, metabolic monitoring', range: 'Personalized based on biomarkers', notes: 'Framework detailed in "Outlive" (2023). Centering principles: exercise is the most powerful longevity "drug". Focus on healthspan not just lifespan.' },
    keyFindings: ['VO2max in top quartile associated with 5x lower all-cause mortality', 'Muscle mass/strength strongest predictor of mortality in elderly', 'Early screening catches disease 10-20 years before symptoms'],
    interactions: [],
    sideEffects: ['Time commitment (10+ hours/week with exercise)', 'Cost of advanced testing'],
    contraindications: [],
    tags: ['protocol', 'framework', 'exercise', 'medicine-3.0', 'evidence-based', 'outlive'],
    estimatedMonthlyCost: { low: 50, mid: 200, high: 500, currency: 'USD' },
  },
  {
    name: 'David Sinclair Longevity Protocol',
    category: 'protocol',
    evidenceGrade: 'C',
    riskProfile: 'low',
    description: 'Protocol based on research by Harvard geneticist David Sinclair (author of "Lifespan"). Centers on the Information Theory of Aging — epigenetic noise accumulation. Core stack: NMN, resveratrol, metformin, with intermittent fasting and cold/heat exposure.',
    mechanisms: ['NAD+ replenishment (NMN)', 'Sirtuin activation (resveratrol + NMN)', 'AMPK activation (metformin)', 'Epigenetic reprogramming support'],
    dosage: { standard: 'NMN 1g, Resveratrol 1g (with yogurt), Metformin 1g (evening)', range: 'Variable — he adjusts based on bloodwork', notes: 'Sinclair has publicly shared his personal protocol. Resveratrol with fat source in morning. NMN morning. Metformin evening (skip on exercise days). Plus vitamin D, K2, aspirin, TMG.' },
    keyFindings: ['Sinclair lab: NMN restored NAD+ levels and improved healthspan in aged mice', 'ICE mice: epigenetic reprogramming reversed aging (Sinclair lab, Cell 2023)', 'Controversial — some peers dispute extrapolation from mouse to human data'],
    interactions: ['Complex multi-drug protocol — interaction mapping important'],
    sideEffects: ['Metformin GI side effects', 'Cost of NMN'],
    contraindications: ['Metformin contraindications apply', 'Individual variation in response'],
    tags: ['protocol', 'sinclair', 'nad+', 'sirtuins', 'epigenetic', 'information-theory'],
    estimatedMonthlyCost: { low: 100, mid: 200, high: 400, currency: 'USD' },
  },
  {
    name: 'Rhonda Patrick Protocol',
    category: 'protocol',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Evidence-focused longevity approach by biomedical scientist Rhonda Patrick PhD (FoundMyFitness). Emphasizes micronutrient optimization, sulforaphane, omega-3, vitamin D, sauna, and exercise. Focuses on nutrient adequacy, genetic polymorphisms (e.g., MTHFR), and hormesis.',
    mechanisms: ['Micronutrient optimization', 'Nrf2 pathway activation (sulforaphane)', 'Omega-3 index optimization (8-12%)', 'Heat shock protein induction (sauna)'],
    dosage: { standard: 'Sulforaphane (moringa/sprouts), Omega-3 (2-4g), Vitamin D (4000-5000 IU), Sauna 4x/week', range: 'Personalized based on genetics and blood work', notes: 'Strong emphasis on food-first approach. Smoothie with diverse micronutrients. Genetic testing to identify vulnerabilities. FoundMyFitness.com for latest protocols.' },
    keyFindings: ['Omega-3 index >8% associated with 5-year longer life expectancy', 'Sauna 4-7x/week: 40% reduction in all-cause mortality (Laukkanen)', 'Sulforaphane activates Nrf2 — upregulates hundreds of protective genes'],
    interactions: [],
    sideEffects: ['Time and cost of comprehensive testing', 'Complexity of tracking'],
    contraindications: [],
    tags: ['protocol', 'micronutrient', 'sulforaphane', 'omega-3', 'sauna', 'evidence-based'],
    estimatedMonthlyCost: { low: 75, mid: 150, high: 300, currency: 'USD' },
  },

  // ═══════════════════════════════════════
  // ADDITIONAL ADVANCED SUPPLEMENTS
  // ═══════════════════════════════════════
  {
    name: 'Nattokinase',
    category: 'supplement',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Fibrinolytic enzyme derived from natto (fermented soybeans). Dissolves fibrin clots, reduces blood viscosity, and supports cardiovascular health. Used widely in Japan for decades. Emerging evidence for reducing spike protein and microclot concerns.',
    mechanisms: ['Fibrinolysis (dissolves fibrin clots)', 'Blood viscosity reduction', 'Blood pressure reduction (ACE inhibition)', 'Anti-inflammatory'],
    dosage: { standard: '2000-4000 FU/day (100-200mg)', range: '2000-6000 FU/day', notes: 'Take on empty stomach (away from food). Measured in fibrinolytic units (FU). NSK-SD form is vitamin K2-free for those on blood thinners.' },
    keyFindings: ['Reduced blood pressure in hypertensive subjects (meta-analysis)', 'Significant fibrinolytic activity demonstrated in human trials', 'Reduced blood viscosity and improved flow in clinical studies'],
    interactions: ['Blood thinners (warfarin, aspirin) — significant interaction', 'Antiplatelet drugs'],
    sideEffects: ['Easy bruising', 'Nosebleeds (rare)', 'GI discomfort'],
    contraindications: ['Bleeding disorders', 'Pre-surgery (stop 2 weeks before)', 'Active bleeding', 'Concurrent anticoagulant therapy (without medical supervision)'],
    tags: ['supplement', 'enzyme', 'cardiovascular', 'fibrinolytic', 'natto', 'blood-flow'],
    estimatedMonthlyCost: { low: 10, mid: 20, high: 40, currency: 'USD' },
  },
  {
    name: 'Serrapeptase',
    category: 'supplement',
    evidenceGrade: 'C',
    riskProfile: 'low',
    description: 'Proteolytic enzyme originally isolated from silkworm gut bacteria. Breaks down inflammatory proteins, fibrin, and scar tissue. Used in European and Japanese medicine for inflammation and pain. Often combined with nattokinase for synergistic fibrinolytic effect.',
    mechanisms: ['Proteolytic — breaks down inflammatory proteins', 'Fibrinolytic activity', 'Scar tissue and biofilm degradation', 'Anti-inflammatory (bradykinin and histamine modulation)'],
    dosage: { standard: '120,000 SPU/day', range: '60,000-240,000 SPU/day', notes: 'Take on empty stomach (2hr from food). Enteric-coated essential. SPU = Serratiopeptidase Units. Often combined with nattokinase.' },
    keyFindings: ['Reduced post-surgical swelling and pain in multiple clinical trials', 'Anti-biofilm properties — may support antibiotic efficacy', 'Approved pharmaceutical in Japan and some European countries'],
    interactions: ['Blood thinners', 'Antibiotics (may enhance penetration)'],
    sideEffects: ['GI discomfort', 'Skin reactions (rare)', 'Bleeding risk'],
    contraindications: ['Bleeding disorders', 'Pre-surgery', 'Concurrent blood thinners'],
    tags: ['supplement', 'enzyme', 'anti-inflammatory', 'proteolytic', 'pain'],
    estimatedMonthlyCost: { low: 8, mid: 15, high: 30, currency: 'USD' },
  },
  {
    name: 'Methylene Blue (Low-Dose)',
    category: 'supplement',
    evidenceGrade: 'C',
    riskProfile: 'medium',
    description: 'Synthetic dye and pharmaceutical with remarkable mitochondrial-enhancing properties at low doses. Acts as an alternative electron carrier in the mitochondrial electron transport chain, bypassing Complex I/III dysfunction. Cognitive enhancer and neuroprotectant with over a century of medical use.',
    mechanisms: ['Alternative electron carrier (mitochondrial ETC bypass)', 'Mitochondrial Complex IV optimization', 'MAO-A inhibition (mood enhancement)', 'Nrf2 activation and autophagy induction'],
    dosage: { standard: '0.5-2mg/kg (typically 15-50mg/day)', range: '0.5-4mg/kg', notes: 'USP pharmaceutical grade essential (NOT industrial dye). Low doses enhance mitochondria, high doses inhibit them (hormetic U-curve). Will turn urine blue-green. Very affordable.' },
    keyFindings: ['Enhanced memory and cognitive function in animal and small human studies', 'Improved mitochondrial function in aged neurons', 'FDA-approved (high dose) for methemoglobinemia — century of safety data at clinical doses'],
    interactions: ['SSRIs and serotonergic drugs (SEROTONIN SYNDROME RISK — serious)', 'MAO inhibitors (CONTRAINDICATED)', 'Psychiatric medications'],
    sideEffects: ['Blue-green urine and stool', 'Blue-tinged skin/sclera', 'Nausea', 'Serotonin syndrome with SSRIs'],
    contraindications: ['SSRI/SNRI use (DANGEROUS — serotonin syndrome)', 'MAO inhibitor use', 'G6PD deficiency (hemolytic anemia)', 'Severe renal impairment'],
    tags: ['supplement', 'mitochondria', 'nootropic', 'neuroprotective', 'pharmaceutical-grade'],
    estimatedMonthlyCost: { low: 5, mid: 15, high: 30, currency: 'USD' },
  },
  {
    name: 'Cistanche tubulosa Extract',
    category: 'supplement',
    evidenceGrade: 'C',
    riskProfile: 'low',
    description: 'Desert-dwelling parasitic plant used in Traditional Chinese Medicine for over 1,800 years as a "yang tonic." Modern research reveals potent anti-aging properties including telomerase activation, neuroprotection, and stem cell proliferation. Known as the "ginseng of the desert."',
    mechanisms: ['Telomerase activation', 'BDNF and NGF upregulation', 'Klotho protein expression increase', 'Stem cell proliferation'],
    dosage: { standard: '100-300mg/day (standardized extract)', range: '100-500mg/day', notes: 'Standardized to echinacoside and acteoside content. Take in morning. Used in Chinese longevity formulas for centuries.' },
    keyFindings: ['Extended lifespan in C. elegans by 20-30%', 'Increased telomerase activity in human peripheral blood mononuclear cells', 'Improved cognitive function and reduced brain aging markers in animal studies'],
    interactions: ['Immunosuppressants (immune-modulating effects)'],
    sideEffects: ['Mild GI discomfort', 'Allergic reaction (rare)'],
    contraindications: ['Autoimmune conditions', 'Pregnancy'],
    tags: ['supplement', 'traditional', 'telomerase', 'neuroprotective', 'adaptogen', 'tcm'],
    estimatedMonthlyCost: { low: 15, mid: 30, high: 55, currency: 'USD' },
  },
  {
    name: 'Glucosamine',
    category: 'supplement',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Amino sugar traditionally used for joint health, but emerging large-scale epidemiological data shows remarkable association with reduced all-cause mortality (18-39% reduction), comparable to regular exercise. May work via mTOR pathway modulation.',
    mechanisms: ['Glycosaminoglycan precursor (cartilage)', 'mTOR pathway modulation', 'Anti-inflammatory', 'Mimics low-carbohydrate state (hexosamine pathway)'],
    dosage: { standard: '1500mg/day', range: '500-3000mg/day', notes: 'Glucosamine sulfate or HCl. Large UK Biobank studies showed mortality benefit. May mimic aspects of fasting via hexosamine pathway.' },
    keyFindings: ['Regular users had 18-39% lower all-cause mortality in UK Biobank (500,000+ participants)', 'Mortality reduction comparable to regular exercise in observational data', 'May activate autophagy via hexosamine pathway — similar to fasting mimicry'],
    interactions: ['Warfarin (may enhance anticoagulant effect)', 'Diabetes medications (monitor glucose)'],
    sideEffects: ['GI discomfort', 'Shellfish allergy concern (if shellfish-derived)'],
    contraindications: ['Shellfish allergy (use synthetic form)', 'Diabetes (monitor glucose)'],
    tags: ['supplement', 'joint', 'mortality', 'mtor', 'affordable', 'well-studied'],
    estimatedMonthlyCost: { low: 8, mid: 15, high: 25, currency: 'USD' },
  },
  {
    name: 'Quercetin',
    category: 'supplement',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Flavonoid with senolytic, anti-inflammatory, and antiviral properties. Part of the dasatinib + quercetin senolytic cocktail studied at Mayo Clinic. Also used standalone for immune support, histamine management, and general anti-inflammatory benefits.',
    mechanisms: ['Senolytic (especially with dasatinib)', 'Anti-inflammatory (NF-κB, COX-2)', 'Antihistamine (mast cell stabilizer)', 'Antiviral (zinc ionophore)'],
    dosage: { standard: '500-1000mg/day', range: '250-2000mg/day', notes: 'Poor bioavailability — use phytosome or liposomal form. As senolytic: 1000mg for 3 days monthly. As daily supplement: 500mg. Zinc ionophore — take with zinc for immune support.' },
    keyFindings: ['Dasatinib + Quercetin cleared senescent cells in human clinical trial (Mayo Clinic)', 'Reduced upper respiratory infections in athletes (meta-analysis)', 'Potent zinc ionophore — enhances intracellular zinc for antiviral activity'],
    interactions: ['Antibiotics (quinolones — may reduce absorption)', 'Blood thinners', 'Cyclosporine'],
    sideEffects: ['Headache', 'GI discomfort', 'Kidney damage (very high doses, rare)'],
    contraindications: ['Kidney disease (high doses)', 'Pregnancy (high doses)'],
    tags: ['supplement', 'flavonoid', 'senolytic', 'antihistamine', 'immune', 'zinc-ionophore'],
    estimatedMonthlyCost: { low: 10, mid: 20, high: 40, currency: 'USD' },
  },
  {
    name: 'Phosphatidylserine (PS)',
    category: 'supplement',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Phospholipid that is a major component of cell membranes, particularly concentrated in brain tissue. Supports cognitive function, cortisol regulation, and cell signaling. FDA-qualified health claim for cognitive decline risk reduction. Levels decline with age.',
    mechanisms: ['Cell membrane fluidity and integrity', 'Cortisol regulation (blunts excess)', 'Acetylcholine and dopamine support', 'Apoptotic signaling (cell membrane asymmetry)'],
    dosage: { standard: '100-300mg/day', range: '100-600mg/day', notes: 'Soy or sunflower derived. FDA-qualified health claim for dementia risk reduction (2003). Take with meals (fat-soluble). May help cortisol management for athletes.' },
    keyFindings: ['Improved cognitive function in elderly with memory complaints (multiple RCTs)', 'FDA-qualified health claim for reduced dementia risk', 'Blunted cortisol response to exercise stress in athletes'],
    interactions: ['Blood thinners (mild anticoagulant effect)', 'Anticholinergic medications'],
    sideEffects: ['GI discomfort', 'Insomnia (if taken late)'],
    contraindications: ['Bleeding disorders'],
    tags: ['supplement', 'phospholipid', 'cognitive', 'cortisol', 'brain', 'fda-claim'],
    estimatedMonthlyCost: { low: 12, mid: 25, high: 45, currency: 'USD' },
  },
  {
    name: 'Shilajit (Purified)',
    category: 'supplement',
    evidenceGrade: 'C',
    riskProfile: 'low',
    description: 'Mineral-rich biomass exudate from Himalayan rocks, used in Ayurvedic medicine for millennia. Contains fulvic acid, dibenzo-alpha-pyrones, and 85+ minerals. Enhances mitochondrial CoQ10 function, increases testosterone, and supports mineral absorption. Must be purified and tested for heavy metals.',
    mechanisms: ['Fulvic acid — mineral absorption enhancement', 'Mitochondrial electron transport support (CoQ10 synergy)', 'Testosterone and fertility support', 'Adaptogenic — stress resistance'],
    dosage: { standard: '250-500mg/day (purified extract)', range: '100-1000mg/day', notes: 'MUST be purified and tested for heavy metals. PrimaVie is most studied branded extract. Take in morning. Traditional use: dissolved in warm milk or water.' },
    keyFindings: ['Increased testosterone by 20% in healthy men (Clinical Ther & Pharm, 2016)', 'Enhanced CoQ10 function in mitochondria (synergistic effect)', 'Improved sperm count and motility in infertile men'],
    interactions: ['Iron supplements (may increase absorption)', 'Diabetes medications'],
    sideEffects: ['GI discomfort', 'Heavy metal toxicity (unpurified products)', 'Allergic reaction (rare)'],
    contraindications: ['Iron overload (hemochromatosis)', 'Active gout'],
    tags: ['supplement', 'mineral', 'adaptogen', 'testosterone', 'ayurvedic', 'traditional'],
    estimatedMonthlyCost: { low: 15, mid: 30, high: 60, currency: 'USD' },
  },
  {
    name: 'Vitamin K2 (MK-7)',
    category: 'supplement',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Fat-soluble vitamin essential for calcium metabolism — directs calcium to bones and teeth while preventing arterial calcification. MK-7 form (from natto) has longest half-life and best clinical evidence. Critical companion to vitamin D3 supplementation.',
    mechanisms: ['Matrix GLA protein activation (prevents arterial calcification)', 'Osteocalcin activation (directs calcium to bones)', 'Vitamin D3 synergy', 'Mitochondrial electron transport participation'],
    dosage: { standard: '100-200mcg MK-7/day', range: '100-500mcg/day', notes: 'Always pair with vitamin D3. MK-7 form preferred (longer half-life than MK-4). Fat-soluble — take with meals. Essential if supplementing high-dose D3.' },
    keyFindings: ['Reduced arterial stiffness in postmenopausal women (3-year RCT)', 'MK-7 supplementation improved bone density and reduced fractures', 'Rotterdam Study: highest K2 intake associated with 50% less arterial calcification'],
    interactions: ['Warfarin (CONTRAINDICATED — directly antagonizes warfarin)', 'Other anticoagulants'],
    sideEffects: ['Minimal', 'GI discomfort (rare)'],
    contraindications: ['Warfarin/coumarin anticoagulant therapy', 'Hypercoagulable states'],
    tags: ['supplement', 'vitamin', 'bone', 'cardiovascular', 'calcification', 'd3-companion'],
    estimatedMonthlyCost: { low: 8, mid: 15, high: 30, currency: 'USD' },
  },
  {
    name: 'Boron',
    category: 'supplement',
    evidenceGrade: 'C',
    riskProfile: 'low',
    description: 'Trace mineral that supports bone health, hormone metabolism, and brain function. Increases free testosterone by reducing SHBG, supports vitamin D metabolism, and has anti-inflammatory properties. Often overlooked but increasingly recognized in longevity circles.',
    mechanisms: ['SHBG reduction (increases free testosterone)', 'Vitamin D metabolism enhancement', 'Bone health (reduces calcium and magnesium excretion)', 'Anti-inflammatory (reduces hs-CRP and TNF-α)'],
    dosage: { standard: '3-6mg/day', range: '3-10mg/day', notes: 'Boron citrate, glycinate, or fructoborate forms. Found in avocados, nuts, dried fruits. Very affordable. Take with meals.' },
    keyFindings: ['Increased free testosterone by 28% and reduced estradiol in 1-week supplementation study', 'Reduced inflammatory markers (hs-CRP, TNF-α) within 1 week', 'Populations with low boron intake have higher arthritis prevalence'],
    interactions: ['Estrogen therapy (may modulate estrogen metabolism)'],
    sideEffects: ['Minimal at recommended doses', 'GI discomfort at very high doses'],
    contraindications: ['Kidney impairment (reduced excretion)'],
    tags: ['mineral', 'hormone', 'testosterone', 'bone', 'affordable', 'overlooked'],
    estimatedMonthlyCost: { low: 3, mid: 6, high: 12, currency: 'USD' },
  },
  {
    name: 'Molecular Hydrogen (H2)',
    category: 'supplement',
    evidenceGrade: 'C',
    riskProfile: 'low',
    description: 'Molecular hydrogen gas (H2) dissolved in water or inhaled. Selectively neutralizes hydroxyl radical (•OH) — the most cytotoxic ROS — without affecting beneficial signaling ROS. Small size allows penetration of all cellular compartments including mitochondria and nucleus.',
    mechanisms: ['Selective hydroxyl radical scavenging', 'Nrf2 pathway activation', 'Anti-inflammatory (NF-κB modulation)', 'Mitochondrial membrane potential maintenance'],
    dosage: { standard: '1-3 hydrogen-rich water tablets/day (1-3 ppm)', range: '0.5-5 ppm water, 1-3x/day', notes: 'Dissolve H2 tablet in water (500ml), drink quickly (H2 escapes). Or use hydrogen water generator. 1000+ published studies. Extremely safe — no known toxic dose.' },
    keyFindings: ['1000+ published studies with wide-ranging benefits', 'Improved metabolic syndrome markers in double-blind RCT', 'Selective antioxidant — only targets harmful •OH radical, preserves beneficial H2O2 and NO signaling'],
    interactions: ['None known'],
    sideEffects: ['Essentially none reported'],
    contraindications: ['None known'],
    tags: ['supplement', 'antioxidant', 'hydrogen', 'selective', 'safe', 'novel'],
    estimatedMonthlyCost: { low: 15, mid: 30, high: 60, currency: 'USD' },
  },
  {
    name: 'Omega-3 (High-Dose EPA)',
    category: 'supplement',
    evidenceGrade: 'A',
    riskProfile: 'low',
    description: 'High-dose EPA (eicosapentaenoic acid) focused omega-3 for cardiovascular and anti-inflammatory benefits beyond standard fish oil. Icosapent ethyl (Vascepa) is the prescription form. Higher EPA:DHA ratio appears more cardioprotective than balanced formulations.',
    mechanisms: ['Triglyceride reduction', 'Anti-inflammatory (resolvin and protectin production)', 'Membrane fluidity optimization', 'Endothelial function improvement'],
    dosage: { standard: '2-4g EPA/day', range: '1-4g EPA/day', notes: 'EPA-focused (3:1 or higher EPA:DHA ratio). Vascepa (icosapent ethyl) is purified EPA — Rx. OTC options: concentrated EPA fish oil. Take with fatty meals for absorption.' },
    keyFindings: ['REDUCE-IT: 4g/day icosapent ethyl reduced cardiovascular events 25% (NEJM)', 'Omega-3 index >8% associated with 5 years greater life expectancy', 'Higher EPA specifically reduces cardiovascular inflammation beyond DHA'],
    interactions: ['Blood thinners (additive antiplatelet effect)', 'High-dose aspirin'],
    sideEffects: ['Fishy burps', 'GI discomfort', 'Easy bruising at very high doses'],
    contraindications: ['Fish/shellfish allergy', 'Active bleeding'],
    tags: ['supplement', 'omega-3', 'epa', 'cardiovascular', 'anti-inflammatory', 'triglycerides'],
    estimatedMonthlyCost: { low: 15, mid: 30, high: 60, currency: 'USD' },
  },
  {
    name: 'Proteolytic Enzyme Blend (Systemic Enzymes)',
    category: 'supplement',
    evidenceGrade: 'C',
    riskProfile: 'low',
    description: 'Systemic enzyme formulations (bromelain, trypsin, chymotrypsin, papain, rutin) taken on empty stomach for systemic anti-inflammatory, fibrinolytic, and immune-modulating effects. Used in German and European integrative medicine for decades. Wobenzym is the most studied brand.',
    mechanisms: ['Systemic proteolysis (inflammatory protein degradation)', 'Fibrinolytic activity', 'Immune complex clearance', 'Anti-edema and analgesic effects'],
    dosage: { standard: '3-6 tablets on empty stomach, 2-3x/day', range: 'Product-specific', notes: 'MUST take on empty stomach (1hr before or 2hr after food). Enteric coating protects from stomach acid. Wobenzym N most studied. German clinical standard.' },
    keyFindings: ['Reduced post-surgical inflammation comparable to NSAIDs in German clinical trials', 'Improved recovery time in athletes (reduced muscle soreness)', 'Immune modulation — reduced autoimmune symptom severity in open-label studies'],
    interactions: ['Blood thinners (additive effect)', 'Antibiotics (may enhance tissue penetration)'],
    sideEffects: ['GI discomfort', 'Allergic reaction (rare)', 'Changes in stool consistency'],
    contraindications: ['Bleeding disorders', 'Pre-surgery (stop 2 weeks before)', 'Severe liver or kidney disease'],
    tags: ['supplement', 'enzyme', 'anti-inflammatory', 'systemic', 'recovery', 'german-medicine'],
    estimatedMonthlyCost: { low: 20, mid: 40, high: 70, currency: 'USD' },
  },
  {
    name: 'Nicotinamide (Niacinamide / Vitamin B3)',
    category: 'supplement',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Amide form of vitamin B3, distinct from niacin (no flushing). NAD+ precursor via the salvage pathway. Shown to reduce skin cancer risk and support DNA repair. Used in dermatology for photoprotection and in oncology for skin cancer prevention at 500mg 2x/day.',
    mechanisms: ['NAD+ precursor (salvage pathway)', 'PARP enzyme support (DNA repair)', 'Skin cancer prevention', 'Anti-inflammatory (immune modulation)'],
    dosage: { standard: '500mg 2x/day', range: '250-1500mg/day', notes: 'Does NOT cause flushing (unlike niacin). ONTRAC trial dose: 500mg 2x/day for skin cancer prevention. Very affordable. Different mechanism from NMN/NR.' },
    keyFindings: ['ONTRAC trial: 23% reduction in new skin cancers at 500mg 2x/day', 'Effectively raises NAD+ via salvage pathway', 'Enhanced DNA repair capacity in UV-exposed skin'],
    interactions: ['Anti-seizure medications', 'Carbamazepine'],
    sideEffects: ['Minimal', 'Mild GI discomfort (rare)', 'Hepatotoxicity (very high doses >3g)'],
    contraindications: ['Active liver disease (high doses)', 'Gout (may increase uric acid at very high doses)'],
    tags: ['supplement', 'nad+', 'b3', 'skin-cancer', 'dna-repair', 'affordable'],
    estimatedMonthlyCost: { low: 5, mid: 10, high: 20, currency: 'USD' },
  },
  {
    name: 'Dihydroberberine (GlucoVantage)',
    category: 'supplement',
    evidenceGrade: 'C',
    riskProfile: 'low',
    description: 'Active metabolite of berberine with 5x better bioavailability. Allows lower dosing with equivalent or superior glucose-lowering effects and fewer GI side effects. GlucoVantage is the branded form. Ideal for those who can\'t tolerate standard berberine doses.',
    mechanisms: ['AMPK activation (same as berberine, better absorbed)', 'Glucose transporter modulation', 'Gut microbiome modulation', 'Lipid metabolism improvement'],
    dosage: { standard: '100-200mg 2-3x/day with meals', range: '100-300mg per dose', notes: '5x better absorbed than berberine — use ~1/5 the dose. GlucoVantage brand most studied. Better GI tolerance than berberine. Take with carb-containing meals.' },
    keyFindings: ['5x greater bioavailability than standard berberine in pharmacokinetic studies', 'Equivalent glucose-lowering at fraction of the dose', 'Significantly fewer GI side effects than standard berberine'],
    interactions: ['CYP enzyme substrates (similar to berberine)', 'Diabetes medications', 'Metformin (use with caution)'],
    sideEffects: ['Mild GI effects (much less than berberine)', 'Hypoglycemia risk with diabetes meds'],
    contraindications: ['Severe liver disease', 'Concurrent metformin (without medical supervision)'],
    tags: ['supplement', 'ampk', 'glucose', 'metabolic', 'berberine-alternative', 'bioavailable'],
    estimatedMonthlyCost: { low: 15, mid: 30, high: 50, currency: 'USD' },
  },
  {
    name: 'Palmitoylethanolamide (PEA)',
    category: 'supplement',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Endogenous fatty acid amide that acts on the endocannabinoid system without binding CB1/CB2 receptors. Anti-inflammatory and analgesic via PPAR-α activation and mast cell downregulation. Nobel laureate Rita Levi-Montalcini studied its neuroprotective properties.',
    mechanisms: ['PPAR-α agonism', 'Mast cell downregulation', 'Endocannabinoid tone modulation (entourage effect)', 'Neuroinflammation reduction'],
    dosage: { standard: '300-600mg 2x/day', range: '300-1200mg/day', notes: 'Micronized or ultra-micronized form for better absorption (OptiPEA). Take with or without food. Onset of pain relief: 2-4 weeks. Studied since 1950s.' },
    keyFindings: ['Reduced chronic pain in multiple RCTs (NNT comparable to pregabalin)', 'Anti-inflammatory without GI side effects of NSAIDs', 'Nobel laureate Levi-Montalcini studied its mast cell and neuroimmune effects'],
    interactions: ['None significant known'],
    sideEffects: ['Minimal — excellent safety profile', 'Mild GI discomfort (rare)'],
    contraindications: ['None established'],
    tags: ['supplement', 'anti-inflammatory', 'pain', 'endocannabinoid', 'neuroprotective', 'safe'],
    estimatedMonthlyCost: { low: 20, mid: 35, high: 60, currency: 'USD' },
  },
  {
    name: 'Spore-Based Probiotics (Bacillus)',
    category: 'supplement',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Spore-forming Bacillus strains (B. subtilis, B. coagulans, B. clausii) that survive stomach acid and colonize the gut more effectively than standard probiotics. Function as "reconditioning" probiotics that modulate the existing microbiome rather than colonizing permanently.',
    mechanisms: ['Gut microbiome reconditioning', 'Short-chain fatty acid production', 'Gut barrier integrity improvement', 'Competitive exclusion of pathogens'],
    dosage: { standard: '1-2 capsules/day', range: 'Product-specific CFU counts', notes: 'MegaSporeBiotic is most studied. Survive stomach acid — no refrigeration needed. True gut colonizers vs transient Lactobacillus strains. Start low (every other day) and increase.' },
    keyFindings: ['Reduced metabolic endotoxemia (LPS leakage) in randomized trial', 'Survived gastric acid and colonized colon (vs <1% survival of standard probiotics)', 'Improved gut barrier function and reduced inflammatory markers'],
    interactions: ['Antibiotics (take 2hr apart)', 'Immunosuppressants (theoretical)'],
    sideEffects: ['Initial die-off symptoms (bloating, gas)', 'GI adjustment period'],
    contraindications: ['Severe immunosuppression', 'Short bowel syndrome'],
    tags: ['supplement', 'probiotic', 'spore-based', 'gut', 'microbiome', 'bacillus'],
    estimatedMonthlyCost: { low: 15, mid: 30, high: 55, currency: 'USD' },
  },
  {
    name: 'Pyruvate Kinase M2 Activator (TEPP-46)',
    category: 'supplement',
    evidenceGrade: 'D',
    riskProfile: 'medium',
    description: 'Research compound that activates pyruvate kinase M2, shifting cellular metabolism from aerobic glycolysis (Warburg effect) back to oxidative phosphorylation. Emerging interest in longevity community for metabolic reprogramming and potential anti-cancer properties.',
    mechanisms: ['PKM2 tetramerization (activating glycolysis completion)', 'Warburg effect reversal', 'Metabolic reprogramming', 'mTOR pathway modulation'],
    dosage: { standard: 'Research compound — no established human dose', range: 'Experimental', notes: 'Research-grade compound. Not commercially available as supplement. Included for awareness — represents emerging metabolic reprogramming approach.' },
    keyFindings: ['Reversed Warburg effect in cancer cells (preclinical)', 'Improved metabolic function in aged cells in vitro', 'Represents novel metabolic reprogramming approach to aging'],
    interactions: ['Unknown — research compound'],
    sideEffects: ['Unknown — limited safety data'],
    contraindications: ['Human use not established'],
    tags: ['experimental', 'metabolism', 'warburg', 'research', 'future'],
    estimatedMonthlyCost: { low: 0, mid: 0, high: 0, currency: 'USD' },
  },
  {
    name: 'Rapamycin Alternatives (Rapalogs)',
    category: 'pharmaceutical',
    evidenceGrade: 'C',
    riskProfile: 'medium',
    description: 'Next-generation mTOR inhibitors and rapalogs designed for better tolerability than rapamycin. Includes everolimus (RTB101) and newer compounds specifically targeting mTORC1 over mTORC2 to reduce side effects while maintaining longevity benefits.',
    mechanisms: ['Selective mTORC1 inhibition', 'Autophagy induction', 'Immune function enhancement (low doses)', 'Senescent cell regulation'],
    dosage: { standard: 'Variable by compound — physician-guided', range: 'Everolimus 0.5mg/week typical', notes: 'Prescription only. Replicel (RTB101/everolimus) showed immune enhancement in elderly at low dose. Goal: mTORC1 inhibition without mTORC2 suppression.' },
    keyFindings: ['Low-dose everolimus enhanced immune response to flu vaccine in elderly by 20% (Mannick et al., Science Translational Medicine)', 'More selective mTORC1 targeting may avoid rapamycin side effects', 'RTB101 (everolimus derivative) in clinical trials for immune aging'],
    interactions: ['CYP3A4 substrates', 'Strong CYP3A4 inhibitors/inducers', 'Vaccines (may affect response)'],
    sideEffects: ['Mouth sores', 'Delayed wound healing', 'Metabolic changes', 'Infections (high doses)'],
    contraindications: ['Active infections', 'Severe hepatic impairment', 'Immunosuppressed patients'],
    tags: ['pharmaceutical', 'mtor', 'rapalog', 'immune', 'autophagy', 'prescription'],
    estimatedMonthlyCost: { low: 30, mid: 80, high: 200, currency: 'USD' },
  },
  {
    name: 'Sleep Optimization Protocol',
    category: 'protocol',
    evidenceGrade: 'A',
    riskProfile: 'low',
    description: 'Comprehensive evidence-based sleep optimization combining environment, behavior, timing, and optional supplementation. Sleep is the foundation of all longevity — poor sleep accelerates every aging pathway. Based on Matthew Walker\'s research and Andrew Huberman\'s protocols.',
    mechanisms: ['Glymphatic clearance (brain waste removal during sleep)', 'Growth hormone secretion (deep sleep)', 'Immune system restoration', 'Memory consolidation and emotional processing'],
    dosage: { standard: '7-9 hours with consistent timing, cool dark room', range: '7-9 hours', notes: 'Temperature: 65-68°F (18-20°C). Dark: blackout curtains. Timing: consistent wake time ±30min. Light: morning sunlight within 30min of waking. No screens 1hr before bed. Supplements if needed: Mg glycinate, L-theanine, apigenin.' },
    keyFindings: ['Sleeping <6hr doubles cardiovascular disease and cancer risk', 'Glymphatic system clears amyloid beta 10x more during sleep', 'Consistent sleep schedule more important than total sleep duration'],
    interactions: [],
    sideEffects: [],
    contraindications: [],
    tags: ['protocol', 'sleep', 'foundational', 'free', 'essential', 'glymphatic'],
    estimatedMonthlyCost: { low: 0, mid: 20, high: 50, currency: 'USD' },
  },
  {
    name: 'Breathwork Protocol (Wim Hof / Box Breathing)',
    category: 'protocol',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Structured breathing practices for stress resilience, immune modulation, and autonomic nervous system control. Wim Hof Method combines cyclic hyperventilation with breath holds, while box breathing activates the parasympathetic system. Both have clinical evidence.',
    mechanisms: ['Autonomic nervous system control', 'Epinephrine and norepinephrine modulation', 'Immune system modulation (Wim Hof)', 'CO2 tolerance training'],
    dosage: { standard: 'Wim Hof: 3 rounds of 30 breaths + hold, daily. Box: 4-4-4-4, 5-10min', range: '5-20 min/day', notes: 'Wim Hof Method: NEVER in water (drowning risk). Box breathing: 4sec inhale-hold-exhale-hold. Physiological sigh (double inhale, long exhale) for acute stress. Free and always available.' },
    keyFindings: ['Wim Hof practitioners voluntarily modulated immune response to endotoxin (PNAS 2014)', 'Box breathing reduced PTSD symptoms in veterans', 'Cyclic hyperventilation increased epinephrine 2-3x (comparable to first-time bungee jump)'],
    interactions: [],
    sideEffects: ['Lightheadedness', 'Tingling (hyperventilation)', 'Emotional release'],
    contraindications: ['Epilepsy', 'Severe cardiovascular disease', 'Pregnancy (intense protocols)', 'Never near water'],
    tags: ['protocol', 'breathwork', 'stress', 'immune', 'autonomic', 'free'],
    estimatedMonthlyCost: { low: 0, mid: 0, high: 0, currency: 'USD' },
  },
  {
    name: 'Time-Restricted Eating (Circadian)',
    category: 'protocol',
    evidenceGrade: 'B',
    riskProfile: 'low',
    description: 'Eating aligned with circadian rhythm — typically finishing food 3+ hours before sleep and emphasizing earlier eating window. Distinct from caloric restriction. Satchin Panda\'s research shows circadian-aligned eating improves metabolic health independent of calorie reduction.',
    mechanisms: ['Circadian clock alignment', 'Metabolic gene expression optimization', 'Improved insulin sensitivity (morning > evening)', 'Gut microbiome circadian rhythm support'],
    dosage: { standard: '10-12 hour eating window, finish 3hr before bed', range: '8-12 hour window', notes: 'Satchin Panda protocol: 10hr window is sweet spot for most. Earlier eating preferred (insulin sensitivity higher in AM). Even without calorie change, metabolic benefits observed. Track with myCircadianClock app.' },
    keyFindings: ['10hr TRE improved metabolic syndrome markers without calorie counting (Panda lab, Cell Metabolism)', 'Firefighters on 10hr TRE: improved blood pressure, glucose, and LDL (RCT)', 'Circadian misalignment (eating late) increases cancer risk independent of calories'],
    interactions: [],
    sideEffects: ['Initial hunger during adjustment', 'Social eating challenges'],
    contraindications: ['Eating disorder history', 'Type 1 diabetes (without medical supervision)', 'Pregnancy'],
    tags: ['protocol', 'circadian', 'fasting', 'metabolic', 'free', 'panda'],
    estimatedMonthlyCost: { low: 0, mid: 0, high: 0, currency: 'USD' },
  },
];

async function seed() {
  const kb = new KnowledgeBase();
  await kb.init();

  console.log('[SeedV3] Seeding V3 product database...');
  let added = 0;
  let skipped = 0;

  for (const product of V3_PRODUCTS) {
    const existing = await kb.getProduct(product.name);
    if (existing) {
      console.log(`  [SKIP] ${product.name} — already exists`);
      skipped++;
      continue;
    }

    await kb.saveProduct({
      ...product,
      id: `prod-${kb.slugify(product.name)}`,
      description: product.description || product.keyFindings?.[0] || '',
      interactions: product.interactions || [],
      sideEffects: product.sideEffects || [],
      contraindications: product.contraindications || [],
      sources: [],
      suppliers: [],
      communityReports: [],
      expertOpinions: [],
    });
    added++;
    console.log(`  [ADD] ${product.name} (${product.category}, evidence: ${product.evidenceGrade})`);
  }

  const total = await kb.listProducts();
  console.log(`\n[SeedV3] Results: ${added} added, ${skipped} skipped (already existed)`);
  console.log(`[SeedV3] Total products in KB: ${total.length}`);
}

seed().catch(console.error);
